global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nodeexporter-1'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['10.1.11.86:9100']

  - job_name: 'nodeexporter-2'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['10.1.11.178:9100']

  - job_name: 'alertmanager'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['10.1.11.86:9093']

  - job_name: 'docker-metrics'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
    - targets: ['10.1.11.117:9323']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080 

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs: 
    - targets:
      - localhost:9093
